// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:1fde212e-b363-44bd-b629-349cdf8feab0",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_BnkJsz2KY",
    "aws_user_pools_web_client_id": "6qgvl86vsll6k3u4kf57t2aft8",
    "oauth": {}
};


export default awsmobile;
